version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/goexamplewebserver
hooks:
  BeforeInstall:
    - location: goexamplewebserver/admin/myservice/stop_service.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: goexamplewebserver/admin/myservice/start_service.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: goexamplewebserver/admin/myservice/stop_service.sh
      timeout: 300
      runas: ec2-user