version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - echo Build started on `date`
      - go get github.com/go-sql-driver/mysql
      - go build *.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app
    - public/**/*
  discard-paths: no
