apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
  - protocol: TCP
    targetPort: 3306
    port: 3306
    name: mysql
