apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-example-webserver
  template:
    metadata:
      labels:
        app: go-example-webserver
    spec:
      containers:
      - name: gowebserver-container
        image: richandersonio/public:go-example-webserver
        ports:
        - containerPort: 8080
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: go-example-webserver
spec:
  selector:
    app: go-example-webserver
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 80
    name: http
  type: LoadBalancer
  